package login_signup;

import dao.UserDAO;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import model.NewOrUpdateUser;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.User;

import util.Authentication;

/**
 *
 * @author sukay
 */
public class SignUp extends javax.swing.JFrame {

    private UserDAO userDAO = new UserDAO();

    /**
     * Creates new form Login
     */
    public SignUp() {
        initComponents();
    }

    //validation
    public class Validator {

        // Validate email address
        public static boolean isValidEmail(String email) {
            String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
            Pattern pattern = Pattern.compile(emailRegex);
            Matcher matcher = pattern.matcher(email);
            return matcher.matches();
        }

        // Validate phone number
        public static boolean isValidPhoneNumber(String phoneNumber) {
            String phoneRegex = "^(\\+?84|0)(3[2-9]|5[2689]|7[0|6-9]|8[1-9]|9[0|3|4|5|7|8|9])(\\d{7})$";
            Pattern pattern = Pattern.compile(phoneRegex);
            Matcher matcher = pattern.matcher(phoneNumber);
            return matcher.matches();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        visible = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Disable2 = new javax.swing.JLabel();
        visible2 = new javax.swing.JLabel();
        txt_phoneNo = new app.bolivia.swing.JCTextField();
        txt_fullname = new app.bolivia.swing.JCTextField();
        SignUp = new rojerusan.RSMaterialButtonCircle();
        LogIn = new rojerusan.RSMaterialButtonCircle();
        jLabel14 = new javax.swing.JLabel();
        txt_email = new app.bolivia.swing.JCTextField();
        jLabel15 = new javax.swing.JLabel();
        txtDate = new app.bolivia.swing.JCTextField();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();

        dateChooser1.setForeground(new java.awt.Color(51, 153, 255));
        dateChooser1.setDateFormat("dd/MM/yyyy");
        dateChooser1.setTextRefernce(txtDate);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-ibooks-250.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setFont(new java.awt.Font("Sitka Text", 2, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("LIBRARY");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("copyright © company name All rights reserved");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 780, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Books are the whole world!");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 340, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 930));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 34, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sign Up");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 290, -1));
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(475, 358, -1, -1));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-invisible-30.png"))); // NOI18N
        disable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        jPanel2.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, 30, -1));

        visible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-eye-30.png"))); // NOI18N
        visible.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        visible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visibleMouseClicked(evt);
            }
        });
        jPanel2.add(visible, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("Full Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 255));
        jLabel4.setText("Phone Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 255));
        jLabel7.setText("Password");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 153, 255));
        jLabel12.setText("Confimred Password");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 630, 220, -1));

        Disable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-invisible-30.png"))); // NOI18N
        Disable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Disable2MouseClicked(evt);
            }
        });
        jPanel2.add(Disable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, 30, -1));

        visible2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-eye-30.png"))); // NOI18N
        visible2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                visible2MouseClicked(evt);
            }
        });
        jPanel2.add(visible2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 660, -1, -1));

        txt_phoneNo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        txt_phoneNo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneNoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_phoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 370, -1));

        txt_fullname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        txt_fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fullnameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 370, -1));

        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        jPanel2.add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 720, 250, 70));

        LogIn.setBackground(new java.awt.Color(0, 255, 51));
        LogIn.setText("Login");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        jPanel2.add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 720, 210, 70));

        jLabel14.setBackground(new java.awt.Color(0, 153, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 255));
        jLabel14.setText("Date of Birth");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        txt_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        txt_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 360, -1));

        jLabel15.setBackground(new java.awt.Color(0, 153, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 255));
        jLabel15.setText("Email");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        txtDate.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        txtDate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel2.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 340, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-calendar-30.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, 360, 30));

        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, 360, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/13900618_5291450.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 650, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, -1, 870));

        setSize(new java.awt.Dimension(1066, 829));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void visible2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visible2MouseClicked
        // TODO add your handling code here:
        jPasswordField2.setEchoChar((char) 8270);
        Disable2.setVisible(true);
        Disable2.setEnabled(true);
        visible2.setEnabled(false);
        visible2.setEnabled(false);
    }//GEN-LAST:event_visible2MouseClicked

    private void Disable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Disable2MouseClicked
        // TODO add your handling code here:
        jPasswordField2.setEchoChar((char) 0);
        Disable2.setVisible(false);
        Disable2.setEnabled(false);
        visible2.setEnabled(true);
        visible2.setEnabled(true);
    }//GEN-LAST:event_Disable2MouseClicked

    private void visibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_visibleMouseClicked
        // TODO add your handling code here:
        jPasswordField1.setEchoChar((char) 8270);
        disable.setVisible(true);
        disable.setEnabled(true);
        visible.setEnabled(false);
        visible.setEnabled(false);
    }//GEN-LAST:event_visibleMouseClicked

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        // TODO add your handling code here:
        jPasswordField1.setEchoChar((char) 0);
        disable.setVisible(false);
        disable.setEnabled(false);
        visible.setEnabled(true);
        visible.setEnabled(true);
    }//GEN-LAST:event_disableMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fullnameActionPerformed

    private void txt_phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneNoActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dateChooser1.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        // TODO add your handling code here:
        NewOrUpdateUser newUser = new NewOrUpdateUser();

        String dobText = txtDate.getText();
        String password = String.valueOf(Authentication.getMd5Password(new String(jPasswordField1.getPassword())));
        String confirmPassword = String.valueOf(Authentication.getMd5Password(new String(jPasswordField2.getPassword())));
        String fullName = txt_fullname.getText();
        String email = txt_email.getText();
        String phoneNumber = txt_phoneNo.getText();
        User existedEmail = userDAO.findUserByEmail(email);
        User existedUser = userDAO.findUserByPhoneNo(phoneNumber);
        if (fullName.isEmpty() || phoneNumber.isEmpty() || email.isEmpty() || dobText.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
          JOptionPane.showMessageDialog(null, "Không được để trống thông tin đăng kí!");
        } else if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(null, "Password không hợp lệ");
        } else if (!Validator.isValidEmail(email)) {
            JOptionPane.showMessageDialog(null, "Email không hợp lệ");
        } else if (!Validator.isValidPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(null, "Số điện trhoại không hợp lệ");
        } else if (existedUser != null) {
            JOptionPane.showMessageDialog(null, "Số điện thoại đã được đăn kí");
        } else if (existedEmail != null) {
         JOptionPane.showMessageDialog(null, "Email đã được đăng kí");
        } else {
            // Insert data into the database

            newUser.setName(fullName);
            newUser.setEmail(email);
            newUser.setPhoneNo(phoneNumber);
            newUser.setPassword(password);

            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Date dobDate = dateFormat.parse(dobText);
                newUser.setDob(dobDate);

            } catch (ParseException e) {
            }
            if (userDAO.addNewUser(newUser)) {

                txt_fullname.setText("");
                txt_email.setText("");
                txt_phoneNo.setText("");
                jPasswordField1.setText("");
                jPasswordField2.setText("");
                txtDate.setText("");
                JOptionPane.showMessageDialog(null, "Đăng kí thành công");
                Login login = new Login();
                login.setVisible(true);
                dispose();

            } else {
                JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thêm");
            }
        }
    }//GEN-LAST:event_SignUpActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Disable2;
    private rojerusan.RSMaterialButtonCircle LogIn;
    private rojerusan.RSMaterialButtonCircle SignUp;
    private com.raven.datechooser.DateChooser dateChooser1;
    private javax.swing.JLabel disable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private app.bolivia.swing.JCTextField txtDate;
    private app.bolivia.swing.JCTextField txt_email;
    private app.bolivia.swing.JCTextField txt_fullname;
    private app.bolivia.swing.JCTextField txt_phoneNo;
    private javax.swing.JLabel visible;
    private javax.swing.JLabel visible2;
    // End of variables declaration//GEN-END:variables
}
