/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import dao.AuthorDAO;
import dao.BookDAO;
import dao.BorrowBookDAO;
import dao.DateConverter;
import dao.UserDAO;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import model.BorrowBook;
import org.bson.types.ObjectId;

/**
 *
 * @author sukay
 */
public class ReturnBooks extends javax.swing.JFrame {

    private BookDAO bookDAO = new BookDAO();
    private UserDAO userDAO = new UserDAO();
    private AuthorDAO authorDAO = new AuthorDAO();
    private BorrowBookDAO borrowBookDAO = new BorrowBookDAO();

    /**
     * Creates new form IssueBooks
     */
    public ReturnBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Main = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        du = new javax.swing.JTextField();
        bo = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rd = new javax.swing.JTextField();
        u = new javax.swing.JTextField();
        ed = new javax.swing.JTextField();
        bd = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        lbl_bookID1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Main.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Main.setForeground(new java.awt.Color(255, 255, 255));
        Panel_Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Panel_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setForeground(new java.awt.Color(255, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel10.setText("        INFORMATION");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 350, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 370, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Return Date:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Book Name:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Borrower:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reason:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, -1, -1));

        du.setEditable(false);
        du.setBackground(new java.awt.Color(255, 51, 51));
        du.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        du.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        du.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        du.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duActionPerformed(evt);
            }
        });
        jPanel3.add(du, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 680, 380, -1));

        bo.setBackground(new java.awt.Color(255, 51, 51));
        bo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        bo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boActionPerformed(evt);
            }
        });
        jPanel3.add(bo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 380, 40));

        jLabel21.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Borrow Date:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Expect Date: ");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        rd.setBackground(new java.awt.Color(255, 51, 51));
        rd.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        rd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        rd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdActionPerformed(evt);
            }
        });
        jPanel3.add(rd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 580, 380, -1));

        u.setEditable(false);
        u.setBackground(new java.awt.Color(255, 51, 51));
        u.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        u.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        u.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uActionPerformed(evt);
            }
        });
        jPanel3.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 380, -1));

        ed.setEditable(false);
        ed.setBackground(new java.awt.Color(255, 51, 51));
        ed.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        ed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ed.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });
        jPanel3.add(ed, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 380, -1));

        bd.setEditable(false);
        bd.setBackground(new java.awt.Color(255, 51, 51));
        bd.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        bd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bd.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        bd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdActionPerformed(evt);
            }
        });
        jPanel3.add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 380, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 650, 890));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Phone No");

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Books_52px_1.png"))); // NOI18N
        jLabel1.setText("Return Book");

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("ISBN");

        jPanel13.setBackground(new java.awt.Color(255, 204, 102));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8-undo-48 (1).png"))); // NOI18N
        jLabel20.setText("Back");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jPanel13.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 50));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(356, 356, 356))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(jLabel3)
                .addGap(80, 80, 80)
                .addComponent(jLabel9)
                .addContainerGap(412, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 490, 910));

        lbl_bookID1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons/signup-library-icon.png"))); // NOI18N
        getContentPane().add(lbl_bookID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 820, 860));

        setSize(new java.awt.Dimension(1574, 811));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        admin ad = new admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void isbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnActionPerformed

    private void duActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duActionPerformed

    private void boActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boActionPerformed

    private void rdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdActionPerformed

    private void uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edActionPerformed

    private void bdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bdActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        // TODO add your handling code here:
        String ISBN = isbn.getText();
        String phoneNo = this.phoneNo.getText();

        if (ISBN.isEmpty() || phoneNo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống thông tin tìm kiếm");
            return;
        }

        ObjectId foundBookId = bookDAO.findIdBookByIsbn(ISBN);
        ObjectId foundUserId = userDAO.findIdUserByPhoneNo(phoneNo);

        boolean bookIdNotFound = foundBookId == null;
        boolean userIdNotFound = foundUserId == null;

        if (bookIdNotFound || userIdNotFound) {
            if (userIdNotFound) {
                JOptionPane.showMessageDialog(null, "Số điện thoại không tồn tại hoặc chưa đúng");
            }
            if (bookIdNotFound) {
                JOptionPane.showMessageDialog(null, "Mã sách không tồn tại hoặc chưa đúng");
            }
            return;
        }

        try {
            BorrowBook bb = borrowBookDAO.findBorrowByUserIdAndBookId(foundBookId, foundUserId);

            if (bb == null) {
                JOptionPane.showMessageDialog(null, "Chưa có thông tin mượn");
            } else {
                BorrowBook updatedBorrowBook = borrowBookDAO.updateBorrowBook(bb.getId());

                if (updatedBorrowBook != null) {
                    BorrowBook bb1 = borrowBookDAO.findBorrowBookById(updatedBorrowBook.getId());
                    bo.setText(bookDAO.findBookById(foundBookId).getBookTitle());
                    u.setText(userDAO.findUserById(foundUserId).getName());
                    bd.setText(DateConverter.DateFormat(bb1.getBorrowedDate().toString()));
                    ed.setText(DateConverter.DateFormat(bb1.getDurationBorrow().toString()));
                    rd.setText(DateConverter.DateFormat(bb1.getReturnDate().toString()));
                    du.setText(bb1.getFineReason());

                    if (bb.getFineAmount() > 0) {
                        String fine = String.format(" %,.0f VND", bb.getFineAmount());
                        JOptionPane.showMessageDialog(null, "Nộp tiền phạt:" + fine);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Không tìm thấy thông tin mượn sách");
                }
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi tìm kiếm mượn sách: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi tìm kiếm mượn sách");
            e.printStackTrace();
        }
    }//GEN-LAST:event_findActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String ISBN = isbn.getText();
        String phone = phoneNo.getText();
        if (phone.isEmpty() || ISBN.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Không được để trống thông tin tìm kiếm");
            return;
        }

        ObjectId foundBookId = bookDAO.findIdBookByIsbn(ISBN);
        ObjectId foundUserId = userDAO.findIdUserByPhoneNo(phone);

        if (foundUserId == null || foundBookId == null) {
            JOptionPane.showMessageDialog(null, "Mã sách hoặc số điện thoại không tồn tại hoặc chưa đúng");
            return;
        }

        try {
            BorrowBook bb3 = borrowBookDAO.findBorrowByUserIdAndBookId(foundBookId,foundUserId );
            if (bb3 != null) {
                borrowBookDAO.updateStt(bb3.getId());
                borrowBookDAO.updateRemainReturn(ISBN);
                JOptionPane.showMessageDialog(null, "Trả sách thành công!");
                bo.setText("");
                u.setText("");
                bd.setText("");
                ed.setText("");
                rd.setText("");
                du.setText("");
                isbn.setText("");
                phoneNo.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Không tìm thấy thông tin mượn sách");
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi cập nhật thông tin");
        }
    }//GEN-LAST:event_addActionPerformed

    private void phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ReturnBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ReturnBooks().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Main;
    private javax.swing.JTextField bd;
    private javax.swing.JTextField bo;
    private javax.swing.JTextField du;
    private javax.swing.JTextField ed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_bookID1;
    private javax.swing.JTextField rd;
    private javax.swing.JTextField u;
    // End of variables declaration//GEN-END:variables
}
