/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import dao.BookDAO;
import dao.BorrowBookDAO;
import dao.DateConverter;
import dao.UserDAO;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.BorrowBook;
import org.bson.types.ObjectId;

/**
 *
 * @author sukay
 */
public class ViewAllRecord extends javax.swing.JFrame {

    private BorrowBookDAO borrowBookDAO = new BorrowBookDAO();
    private BookDAO bookDAO = new BookDAO();
    private UserDAO userDAO = new UserDAO();

    private DefaultTableModel tblModel = new DefaultTableModel();
    private Map<Integer, BorrowBook> borrowTableRowIndxWithBorrowId = new HashMap<>();

    DefaultComboBoxModel<String> comModelChoiceStatus = new DefaultComboBoxModel();

    /**
     * Creates new form ViewAllRecord
     */
    public ViewAllRecord() {
        initComponents();

        tblModel.addColumn("STT");
        tblModel.addColumn("Book Name");
        tblModel.addColumn("Borrower");
        tblModel.addColumn("Borrow Date");
        tblModel.addColumn("Expected Date");
        tblModel.addColumn("Return Date");
        tblModel.addColumn("Reason");
        tblModel.addColumn("Fine Money");
        tblModel.addColumn("Status");

        tblBB.setModel(tblModel);
        tblBB.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblBB.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblBB.getColumnModel().getColumn(1).setPreferredWidth(450);
        tblBB.getColumnModel().getColumn(2).setPreferredWidth(400);
        tblBB.getColumnModel().getColumn(3).setPreferredWidth(200);
        tblBB.getColumnModel().getColumn(4).setPreferredWidth(200);
        tblBB.getColumnModel().getColumn(5).setPreferredWidth(200);
        tblBB.getColumnModel().getColumn(6).setPreferredWidth(200);
        tblBB.getColumnModel().getColumn(7).setPreferredWidth(200);
        tblBB.getColumnModel().getColumn(8).setPreferredWidth(188);

        comModelChoiceStatus.addElement("Đang mượn");
        comModelChoiceStatus.addElement("Đã trả");
        choose.setModel(comModelChoiceStatus);

        loadAllBorrowBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        isbn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        choose = new javax.swing.JComboBox<>();
        dele = new rojerusan.RSMaterialButtonRectangle();
        se = new rojerusan.RSMaterialButtonRectangle();
        showAll = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBB = new rojeru_san.complementos.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminIcons/adminIcons/icons8-undo-48 (1).png"))); // NOI18N
        jLabel17.setText("Back");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 0, 51));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ISBN :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AddNewBookIcons/AddNewBookIcons/icons8_Literature_100px_1.png"))); // NOI18N
        jLabel10.setText("Views All Records");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 50, 340, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 170, 360, 10));
        jPanel2.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 40));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Status :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 40));

        choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(choose, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 260, 40));

        dele.setBackground(new java.awt.Color(255, 0, 51));
        dele.setText("DELETE");
        dele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleActionPerformed(evt);
            }
        });
        jPanel2.add(dele, new org.netbeans.lib.awtextra.AbsoluteConstraints(1890, 110, 170, 60));

        se.setBackground(new java.awt.Color(255, 0, 51));
        se.setText("Search");
        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });
        jPanel2.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 170, 60));

        showAll.setBackground(new java.awt.Color(255, 0, 51));
        showAll.setText("SHOW ALL");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });
        jPanel2.add(showAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 110, 170, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2200, 240));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        tblBB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblBB.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        tblBB.setFuenteFilas(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblBB.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tblBB.setFuenteHead(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tblBB.setRowHeight(70);
        jScrollPane2.setViewportView(tblBB);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 2150, 860));

        setSize(new java.awt.Dimension(2144, 1100));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        // TODO add your handling code here:
        admin ad = new admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        admin ad = new admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jPanel11MouseClicked

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        // TODO add your handling code here:
        loadAllBorrowBooks();
    }//GEN-LAST:event_showAllActionPerformed

    private void deleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBB.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        try {
            ObjectId id = borrowTableRowIndxWithBorrowId.get(selectedRow).getId();
            if (borrowBookDAO.checkBookWasReturned(id)) {
                JOptionPane.showMessageDialog(null, "Chưa trả sách khong the xoa");

            } else {
                if (borrowBookDAO.deleteBorrowBook(id)) {
                    this.loadAllBorrowBooks();
                    JOptionPane.showMessageDialog(null, "Xóa sach thanh cong");

                } else {
                    JOptionPane.showMessageDialog(null, "Không thể xóa sách");

                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Lỗi khi xóa sách");

        }
    }//GEN-LAST:event_deleActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
        String ISBN = isbn.getText();
        String select = (String) comModelChoiceStatus.getSelectedItem();

        if (ISBN.isEmpty()) {
            List<BorrowBook> borrowBooks = borrowBookDAO.findBorrowBooksByStt(select);
            updateUITable(borrowBooks);
        } else {
            Object foundBookId = bookDAO.findIdBookByIsbn(ISBN);
            if (foundBookId == null) {
                JOptionPane.showMessageDialog(null, "Mã sách ko tồn tại hoặc chưa đúng");
            }
            try {
                List<BorrowBook> borrowBooks = borrowBookDAO.findBorrowBooksByUserIdAndBookId(select, foundBookId);
                updateUITable(borrowBooks);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi tìm kiếm mượn sách");
            }
        }
    }
    private void updateUITable(List<BorrowBook> borrowBooks) {
        DefaultTableModel tblModel = (DefaultTableModel) tblBB.getModel();
        tblModel.setRowCount(0);
        for (int idx = 0; idx < borrowBooks.size(); idx++) {
            BorrowBook borrow = borrowBooks.get(idx);
            Object[] row = {
                idx,
                bookDAO.findBookById(borrow.getBookId()).getIsbn() + " : " + bookDAO.findBookById(borrow.getBookId()).getBookTitle(),
                userDAO.findUserById(borrow.getUserId()).getPhoneNo()+ " - " + userDAO.findUserById(borrow.getUserId()).getName(),
                DateConverter.DateFormat(borrow.getBorrowedDate().toString()),
                DateConverter.DateFormat(borrow.getDurationBorrow().toString()),
                (borrow.getReturnDate() != null) ? DateConverter.DateFormat(borrow.getReturnDate().toString()) : "0",
                borrow.getDuration(),
                borrow.getFineAmount(),
                borrow.getBorrowStatus()
            };
            tblModel.addRow(row);
        }
    }//GEN-LAST:event_seActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAllRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAllRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choose;
    private rojerusan.RSMaterialButtonRectangle dele;
    private javax.swing.JTextField isbn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSMaterialButtonRectangle se;
    private rojerusan.RSMaterialButtonRectangle showAll;
    private rojeru_san.complementos.RSTableMetro tblBB;
    // End of variables declaration//GEN-END:variables

    private void loadAllBorrowBooks() {
        SwingUtilities.invokeLater(() -> {
            
            while (tblModel.getRowCount() > 0) {
                tblModel.removeRow(0);
            }
            List<BorrowBook> list = borrowBookDAO.findAllBorrowBooks();
            int idx = 0;
            for (BorrowBook bb : list) {
                String re = (bb.getFineReason() != null)? bb.getFineReason() : "0";
                Object[] row = {
                    idx,
                 bb.getBook() + " - " + bb.getBook().getIsbn(),
                  bb.getUser() + " - " +  bb.getUser().getPhoneNo(),
                    DateConverter.DateFormat(bb.getBorrowedDate().toString()),
                    DateConverter.DateFormat(bb.getDurationBorrow().toString()),
                    (bb.getReturnDate() != null) ? DateConverter.DateFormat(bb.getReturnDate().toString()) : "0",
                    re,
                    String.format("%,.0f VND", bb.getFineAmount()),
                    bb.getBorrowStatus()
                };
                tblModel.addRow(row);
                borrowTableRowIndxWithBorrowId.put(idx++, bb);
            }
        });
    }

}
